Repository QubesOS/qubes-core-admin, pull requests merged in 2025-06, with the labels that each got.

#683 tests: give it more time to start recording
  qubes/tests/integ/audio.py
Labels: openqa-pending, openqa-group-2

#687 tests: test handling long window titles
  qubes/tests/integ/vm_qrexec_gui.py
Labels: openqa-pending

#685 Rename on_domain_shutdown to avoid DispVM clobbering the function
  qubes/vm/dispvm.py
  qubes/vm/mix/net.py
Labels: openqa-pending, openqa-group-1

#680 Late GUID for preloaded disposables
  Makefile
  linux/autostart/Makefile
  linux/autostart/qubes-preload-dispvm.desktop
  qubes/tests/api_admin.py
  qubes/tests/integ/dispvm.py
  qubes/vm/dispvm.py
  qubes/vm/mix/dvmtemplate.py
  rpm_spec/core-dom0.spec.in
Labels: openqa-group-1
