Repository QubesOS/qubes-core-admin, pull requests merged in 2025-04, with the labels that each got.

#670 tests: minor fixes
  qubes/tests/__init__.py
  qubes/tests/integ/audio.py
  qubes/tests/integ/vm_qrexec_gui.py
Labels: openqa-pending, openqa-group-2

#672 Move device-related exceptions to the exc module
  qubes/device_protocol.py
  qubes/devices.py
  qubes/exc.py
  qubes/ext/block.py
  qubes/storage/__init__.py
  qubes/storage/callback.py
  qubes/storage/file.py
  qubes/storage/kernels.py
  qubes/storage/lvm.py
  qubes/storage/reflink.py
  qubes/storage/zfs.py
  qubes/tests/api_admin.py
  qubes/tests/devices.py
  qubes/tests/integ/audio.py
  qubes/tests/integ/basic.py
  qubes/tests/storage_callback.py
  qubes/tests/storage_zfs.py
  qubes/vm/qubesvm.py
Labels: openqa-pending

#667 ext/pci: implement PCI path for device identification
  doc/example.xml
  doc/qubes-devices.rst
  qubes/ext/pci.py
  qubes/tests/devices_pci.py
  qubes/tests/vm/init.py
  qubes/tests/vm/qubesvm.py
  qubes/utils.py
  qubes/vm/__init__.py
  relaxng/qubes.rng
  rpm_spec/core-dom0.spec.in
  templates/libvirt/devices/pci.xml
  tests-data/sysfs/sys/bus/pci/devices/0000:00:08.1
  tests-data/sysfs/sys/bus/pci/devices/0000:00:18.0
  tests-data/sysfs/sys/bus/pci/devices/0000:00:18.1
  tests-data/sysfs/sys/bus/pci/devices/0000:00:18.2
  tests-data/sysfs/sys/bus/pci/devices/0000:00:18.3
  tests-data/sysfs/sys/bus/pci/devices/0000:00:18.4
  tests-data/sysfs/sys/bus/pci/devices/0000:02:00.0
  tests-data/sysfs/sys/bus/pci/devices/0000:02:00.2
  tests-data/sysfs/sys/bus/pci/devices/0000:c0:03.5
  tests-data/sysfs/sys/bus/pci/devices/0000:c5:00.0
  tests-data/sysfs/sys/bus/pci/devices/0000:c6:00.0
  tests-data/sysfs/sys/devices/pci0000:00/0000:00:08.1/secondary_bus_number
  tests-data/sysfs/sys/devices/pci0000:00/0000:00:08.1/subordinate_bus_number
  tests-data/sysfs/sys/devices/pci0000:c0/0000:c0:03.5/0000:c5:00.0/secondary_bus_number
  tests-data/sysfs/sys/devices/pci0000:c0/0000:c0:03.5/0000:c5:00.0/subordinate_bus_number
  tests-data/sysfs/sys/devices/pci0000:c0/0000:c0:03.5/secondary_bus_number
  tests-data/sysfs/sys/devices/pci0000:c0/0000:c0:03.5/subordinate_bus_number
Labels: openqa-pending

#674 tests: only close watch fd for LocalVM
  qubes/tests/__init__.py
Labels: openqa-pending, openqa-group-1

#675 tests: fix creating test qrexec services
  qubes/tests/integ/qrexec.py
Labels: openqa-pending

#669 tests: simple end-to-end remote qrexec test
  qubes/tests/__init__.py
  qubes/tests/integ/misc.py
Labels: openqa-pending

#676 Fix handling larger root complex with PCI path
  qubes/tests/__init__.py
  qubes/tests/integ/misc.py
Labels: openqa-pending

#673 Assure paused domains prior to suspending remain paused
  qubes/api/internal.py
  qubes/tests/api_internal.py
Labels: openqa-pending

#656 Add free-form text to qube for notes, comments, ...
  .gitlab-ci.yml
  Makefile
  qubes/api/admin.py
  qubes/backup.py
  qubes/tests/api_admin.py
  qubes/tests/vm/qubesvm.py
  qubes/vm/qubesvm.py
  rpm_spec/core-dom0.spec.in
Labels: openqa-pending
